theme: jekyll-theme-minimal
title: Parallel Logic Expert with Operator Routing
description: Course project for Oregon State University AI 535 — Differentiable fuzzy logical operators and learned operator routing for transformer backbones.
url: https://ancorro.github.io
repository: Ancorro/logic-expert-public
